# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8081/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/cloudevents+json

{
  "contenttype": "application/json",
  "data": {
    "sliProvider": "dynatrace",
    "project": "sockshop",
    "service": "carts",
    "stage": "dev",
    "start": "2019-10-28T15:44:27.152330783Z",
    "end": "2019-10-28T15:54:27.152330783Z",
    "indicators": ["throughput", "error_rate", "request_latency_p50", "request_latency_p90", "request_latency_p95"],
    "customFilters": [
      { "key" : "dynatraceEntityName", "value": "HealthCheckController" },
      { "key" : "tags", "value": "test-subject:true" }
    ]
  },
  "id": "b3c3c357-eb3d-4f90-b26e-9ebfedfb8dbf",
  "source": "lighthouse-service",
  "specversion": "0.2",
  "time": "2019-10-14T08:00:09.416Z",
  "type": "sh.keptn.internal.event.get-sli",
  "shkeptncontext": "b0704d01-e936-40ff-b6e3-6fb29790b9ef"
}
###
