apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: keptncontrib/dynatrace-sli-service
      docker:    # 	beta describes an artifact built from a Dockerfile.
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  helm:
    flags:
      upgrade: ["--reuse-values"]
    releases:
      - name: dynatrace-sli-service # needs to be the same name as currently used (check via helm ls -n keptn)
        namespace: keptn # needs to be the same namespace as where the helm-chart is currently deployed
        # upgradeOnChange: true
        # recreatePods: false # don't recreate all pods
        artifactOverrides:
          image: keptncontrib/dynatrace-sli-service
        overrides:
          distributor:
            image:
              tag: 0.8.0
        chartPath: chart
