apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dynatrace-sli-service.serviceAccountName" . }}
  labels:
    {{- include "dynatrace-sli-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dynatrace-sli-service.serviceAccountName" . }}-secrets
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dynatrace-sli-service.serviceAccountName" . }}-secrets
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dynatrace-sli-service.serviceAccountName" . }}-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "dynatrace-sli-service.serviceAccountName" . }}
